### ISSUE TITLE
ERROR: IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by aguel** [hyperledger-labs/minifabric#181]
### **Minifab Execution Context**
```
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=payment.net
    HOST_ADDRESSES=10.148.0.7
    WORKING_DIRECTORY: /home/aguel
```
### **spec.yaml**
```
fabric:
  cas:
  - "ca1.org0.payment.net"
  peers:
  - "peer1.org0.payment.net"
  orderers:
  - "orderer1.payment.net"
```   

### **ERROR**
```
# Preparing for the following operations: *********************
  verify options, download images, generate certificates, start network, network status, channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
.................
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  download images
............
# Running operation: ******************************************
  generate certificates
..........................................................................
# Running operation: ******************************************
  start network
........................
# Running operation: ******************************************
  network status
...
# Current Minifabric image ID and created at date time ********
  bfec58cea87c   2021-04-04 14:23:11 +0000 UTC
.....
# Docker node status ******************************************
  b26f84def3_cli : Up 9 seconds
  ca1.org0.payment.net : Up 10 seconds
  orderer1.payment.net : Up 11 seconds
  peer1.org0.payment.net : Up 13 seconds

# Fabric network peer and orderer node health status **********
  peer1.org0.payment.net "OK"
  orderer1.payment.net "OK"
  Network Status: 100%

# Running operation: ******************************************
  channel create
...
# Select a peer for channel creation. *************************

  _Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 585, in _execute
      self._task.post_validate(templar=templar)
    File "/usr/lib/python3.8/site-packages/ansible/playbook/task.py", line 307, in post_validate
      super(Task, self).post_validate(templar)
    File "/usr/lib/python3.8/site-packages/ansible/playbook/base.py", line 431, in post_validate
      value = templar.template(getattr(self, name))
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 835, in template
      d[k] = self.template(
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 789, in template
      result = self.do_template(
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 1057, in do_template
      res = j2_concat(rf)
    File "<template>", line 16, in root
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 255, in wrapper
      ret = func(*args, **kwargs)
    File "/usr/lib/python3.8/site-packages/ansible/plugins/filter/core.py", line 237, in rand
      return r.choice(end)
    File "/usr/lib/python3.8/random.py", line 290, in choice
      raise IndexError('Cannot choose from an empty sequence') from None
  IndexError: Cannot choose from an empty sequence_
```

Been getting this error even after "cleanup" and even on "fresh installed OS".
On the otherhand, without using any "spec.yaml", and simply doing "minifab up" works perfectly. 
Any thoughts? @litong01 

**PS: Running the latest minifabric update and the latest minifabric image**

**Comment by litong01** [comment]
Your orderer org and peer org cannot be the same. Please close this issue.

**Comment by aguel** [comment]
Actually the "specs.yaml" is correct, nonetheless closing this ticket as I figured out the problem is with the CLI parameters. Specifying "-o org0.payment.net" instead of "-o payment.net" resolved the issue. My mistake, but keeping this as reference for others. @litong01

**Comment by aguel** [comment]
Actually the "specs.yaml" is correct, nonetheless closing this ticket as I figured out the problem is with the CLI parameters. Specifying "-o org0.payment.net" instead of "-o payment.net" resolved the issue. My mistake, but keeping this as reference for others. @litong01

**Comment by litong01** [comment]
the spec.yaml is not correct. It will fail in other aspect. You can not have orderer and peer org the same.

**Comment by aguel** [comment]
Can you please enlighten me what is the difference between the official spec.yaml and the one I have created? May I please know which part is incorrect? The only difference I can see is the change from "example.com" to "payment.net" or maybe I missed something here? Unless you are referring to a possible mistake of using "**orderer1.org0.payment.net**" which is not the case here.

### **EXAMPLE**
```
fabric:
  cas:
  - "ca1.org0.example.com"
  peers: 
  - "peer1.org0.example.com"
  orderers:
  - "orderer1.example.com"
```

### **MY spec.yaml**
```
fabric:
  cas:
  - "ca1.org0.payment.net"
  peers:
  - "peer1.org0.payment.net"
  orderers:
  - "orderer1.payment.net"
```

**Comment by litong01** [comment]
@aguel I missed org0 for the peer org. You do have two different orgs though they share the common subdomain name. So what you have two orgs, one is org0.payment.net, one is payment.net. Fabric network will consider them two completely organizations. So I think you are ok. I did not see the org0 for the peer org. Sorry about the false alarm.

**Comment by aguel** [comment]
Thank you very much.
