### ISSUE TITLE
Hyperledger Explorer Not working

### ISSUE THREAD

**Issue by skulos** [hyperledger-labs/minifabric#97]
I ran the following command:
```
$ mkdir -p ~/mywork && cd ~/mywork && curl -o minifab -sL https://tinyurl.com/yxa2q6yr && chmod +x minifab
```
like the README.md suggests. Then I ran:
```
$ tree
.
└── minifab

0 directories, 1 file
```
And `up` 
<pre>
$ ./minifab up
Using default spec file
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES= 111.222.333.444 <b>!! (changed) !! </b>
    WORKING_DIRECTORY: /home/hendreh/mywork
...
# Preparing for the following operations: *********************
  verify options, download images, generate certificates, start network, network status, channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
.................
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  download images
............
# Running operation: ******************************************
  generate certificates
............................................................................................................................................
# Running operation: ******************************************
  start network
.......................
# Running operation: ******************************************
  network status
......
# Docker node status ******************************************
  c31e42d698_cli : Up 6 seconds
  ca1.org1.example.com : Up 7 seconds
  ca1.org0.example.com : Up 8 seconds
  orderer3.example.com : Up 9 seconds
  orderer2.example.com : Up 10 seconds
  orderer1.example.com : Up 10 seconds
  peer2.org1.example.com : Up 11 seconds
  peer1.org1.example.com : Up 12 seconds
  peer2.org0.example.com : Up 13 seconds
  peer1.org0.example.com : Up 13 seconds

# Fabric network peer and orderer node health status **********
  peer1.org0.example.com "OK"
  peer2.org0.example.com "OK"
  peer1.org1.example.com "OK"
  peer2.org1.example.com "OK"
  orderer1.example.com "OK"
  orderer2.example.com "OK"
  orderer3.example.com "OK"

# Running operation: ******************************************
  channel create
......
# Running operation: ******************************************
  channel join
...........................
# Running operation: ******************************************
  anchor update
............
# Running operation: ******************************************
  profile generation
.................................
# Running operation: ******************************************
  cc install
...........................
# Running operation: ******************************************
  cc approve
......
# Running operation: ******************************************
  cc commit
.............
# Running operation: ******************************************
  cc initialize
......
# Running operation: ******************************************
  discover
........................
# Discover endorsers results **********************************
  Chaincode endorsers file: ./vars/discover/mychannel/simple_endorsers.json
# Discover orderers results ***********************************
  Channel orderers file: ./vars/discover/mychannel/ordererendpoints.json

# STATS *******************************************************
minifab: ok=412	failed=0	

real	4m1.284s
user	2m4.994s
sys	0m22.177s
</pre>

And then finally starting up Hyperledger Explorer:
<pre>
$ ./minifab explorerup
Using default spec file
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=111.222.333.444 <b>!! (changed) !! </b>
    WORKING_DIRECTORY: /home/hendreh/mywork
...
# Preparing for the following operations: *********************
  verify options, start explorer
.................
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  start explorer
..........
# Wait for explorer db container to be ready ******************
  
.
# Explorer endpoint for c31e42d698_net  ***********************
  "Default username: exploreradmin"
  "Default password: exploreradminpw"
  "Website address:  http://172.23.0.248:7201"
  

# STATS *******************************************************
minifab: ok=38	failed=0	

real	0m15.663s
user	0m8.949s
sys	0m1.626s
</pre>

The logs of the container are:
```
> Executing task: docker logs -f dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47 <

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/opt/explorer/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Terminal will be reused by tasks, press any key to close it.
```

And the _explorer:latest.json_ is:
```
{
    "Id": "dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47",
    "Created": "2020-10-08T09:53:07.979021214Z",
    "Path": "docker-entrypoint.sh",
    "Args": [
        "node",
        "/opt/explorer/main.js"
    ],
    "State": {
        "Status": "exited",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 1,
        "Error": "",
        "StartedAt": "2020-10-08T09:53:08.478960276Z",
        "FinishedAt": "2020-10-08T09:53:08.595489234Z"
    },
    "Image": "sha256:023148be39b8144ec72dd298158037c8a26bde756842bb7b2c2aad19b5241aa9",
    "ResolvConfPath": "/var/lib/docker/containers/dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47/hostname",
    "HostsPath": "/var/lib/docker/containers/dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47/hosts",
    "LogPath": "/var/lib/docker/containers/dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47/dd22ee175c9f149556a9444db8c33073cdf414b185e2f96a42eea54c81eedb47-json.log",
    "Name": "/explorer.c31e42d698_net",
    "RestartCount": 0,
    "Driver": "overlay2",
    "Platform": "linux",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "docker-default",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "explorerwallet.c31e42d698_net:/opt/wallet",
            "/home/hendreh/mywork/vars/explorer/mychannel_config.json:/opt/explorer/app/platform/fabric/config.json",
            "/home/hendreh/mywork/vars/explorer:/opt/explorer/app/platform/fabric/connection-profile",
            "/home/hendreh/mywork/vars/keyfiles:/keyfiles"
        ],
        "ContainerIDFile": "",
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "NetworkMode": "c31e42d698_net",
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "7201"
                }
            ]
        },
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "AutoRemove": false,
        "VolumeDriver": "",
        "VolumesFrom": null,
        "CapAdd": null,
        "CapDrop": null,
        "Capabilities": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IpcMode": "shareable",
        "Cgroup": "",
        "Links": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "SecurityOpt": null,
        "UTSMode": "",
        "UsernsMode": "",
        "ShmSize": 67108864,
        "Runtime": "runc",
        "ConsoleSize": [
            0,
            0
        ],
        "Isolation": "",
        "CpuShares": 0,
        "Memory": 0,
        "NanoCpus": 0,
        "CgroupParent": "",
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteIOps": null,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "Devices": [],
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "OomKillDisable": false,
        "PidsLimit": null,
        "Ulimits": null,
        "CpuCount": 0,
        "CpuPercent": 0,
        "IOMaximumIOps": 0,
        "IOMaximumBandwidth": 0,
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ]
    },
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/fe660142435be5c58259149e594eca2c2ec58c0f566898c151b340d570da6ee1-init/diff:/var/lib/docker/overlay2/82482c0501524e3d81309cb7711e3bf2c2387e0baa43537a9c1633b324069df0/diff:/var/lib/docker/overlay2/f15e05ebe606368f0f7d9ed70bad991496ebb2bc56aa2c78f01dbbd6842b29f3/diff:/var/lib/docker/overlay2/e42f3b293110fed4ddf6a95887c752427f3a71b5be885071fc83ceaf87171bf0/diff:/var/lib/docker/overlay2/10f54f8fb793a6f1d598836ffaba3c9bb3d307548361e17891eea75d87e26716/diff:/var/lib/docker/overlay2/7eadc96799cac0355e2bf93633758b5079c5f12fd7ec73f948bfa2e86772fcbe/diff:/var/lib/docker/overlay2/16a40ac83c29bc7e3643a00c3f3393f1c7456b549b6d5555bda119d6d472e8af/diff:/var/lib/docker/overlay2/cd8b577b3b617d440b7211c66e09578151bb70e37da5e957d7fd91b39ce400f4/diff:/var/lib/docker/overlay2/232571861eab65afd736afd3e8d9fc92274eea83cf5f020db9ee796b8c2d796e/diff:/var/lib/docker/overlay2/2a91dd908dea6a515afaafcb1858765560d4efccc2d40280f9d950dd94c51d65/diff",
            "MergedDir": "/var/lib/docker/overlay2/fe660142435be5c58259149e594eca2c2ec58c0f566898c151b340d570da6ee1/merged",
            "UpperDir": "/var/lib/docker/overlay2/fe660142435be5c58259149e594eca2c2ec58c0f566898c151b340d570da6ee1/diff",
            "WorkDir": "/var/lib/docker/overlay2/fe660142435be5c58259149e594eca2c2ec58c0f566898c151b340d570da6ee1/work"
        },
        "Name": "overlay2"
    },
    "Mounts": [
        {
            "Type": "volume",
            "Name": "explorerwallet.c31e42d698_net",
            "Source": "/var/lib/docker/volumes/explorerwallet.c31e42d698_net/_data",
            "Destination": "/opt/wallet",
            "Driver": "local",
            "Mode": "z",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "bind",
            "Source": "/home/hendreh/mywork/vars/explorer/mychannel_config.json",
            "Destination": "/opt/explorer/app/platform/fabric/config.json",
            "Mode": "",
            "RW": true,
            "Propagation": "rprivate"
        },
        {
            "Type": "bind",
            "Source": "/home/hendreh/mywork/vars/explorer",
            "Destination": "/opt/explorer/app/platform/fabric/connection-profile",
            "Mode": "",
            "RW": true,
            "Propagation": "rprivate"
        },
        {
            "Type": "bind",
            "Source": "/home/hendreh/mywork/vars/keyfiles",
            "Destination": "/keyfiles",
            "Mode": "",
            "RW": true,
            "Propagation": "rprivate"
        }
    ],
    "Config": {
        "Hostname": "explorer.c31e42d698_net",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "DATABASE_USERNAME=hppoc",
            "LOG_LEVEL_APP=debug",
            "DISCOVERY_AS_LOCALHOST=false",
            "DATABASE_HOST=explorerdb.c31e42d698_net",
            "DATABASE_DATABASE=fabricexplorer",
            "DATABASE_PASSWD=password",
            "LOG_LEVEL_DB=debug",
            "LOG_LEVEL_CONSOLE=debug",
            "LOG_CONSOLE_STDOUT=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=10.19.0",
            "YARN_VERSION=1.21.1",
            "DATABASE_PORT=5432",
            "DATABASE_NAME=fabricexplorer",
            "EXPLORER_APP_ROOT=app",
            "DEFAULT_WORKDIR=/opt",
            "EXPLORER_APP_PATH=/opt/explorer"
        ],
        "Cmd": [
            "node",
            "/opt/explorer/main.js"
        ],
        "Image": "hyperledger/explorer:latest",
        "Volumes": null,
        "WorkingDir": "/opt/explorer",
        "Entrypoint": [
            "docker-entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {}
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "b9af051c14fcb9842b1e978d6a7ca5012e048e4062fc591beddba8d9fba4e2f1",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/b9af051c14fc",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": {
            "c31e42d698_net": {
                "IPAMConfig": null,
                "Links": null,
                "Aliases": [
                    "dd22ee175c9f"
                ],
                "NetworkID": "d5dff37d45768b05f2afbfa30be38fed7fae015e0bf327bf9ed66e91e56e14c5",
                "EndpointID": "",
                "Gateway": "",
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "",
                "DriverOpts": null
            }
        }
    },
    "CreatedTime": 1602150787979
}
```

**Comment by litong01** [comment]
Do a minifabric update. That is all it takes to fix the problem.

minifab update

**Comment by skulos** [comment]
https://github.com/hyperledger-labs/minifabric/pull/98
